#!/usr/bin/env python3

import os
import sys

import click
import git

import banana


@click.command()
@click.option("--debug", is_flag=True)
@click.argument("db_filename")
@click.argument("rev_range")
def main(debug, db_filename, rev_range):
    """Insert commit details into the database."""
    if debug:
        banana.Logger_init(log_level="debug")

    mydb = banana.DataBase(db_filename)
    repo = git.Repo(os.getcwd())
    for commit in repo.iter_commits(rev_range):
        if len(commit.parents) != 1:
            continue

        try:
            mydb.commit.insert_commit(commit)
        except banana.RowExistsError:
            print(f"Commit exists already: {commit}", file=sys.stderr)


if __name__ == "__main__":
    main()  # pylint: disable=E1120
